// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj_wX613_ttr85hXPjLZMtZAJBte8AFqM',
    appId: '1:280801840179:web:6365ac052b70162775e746',
    messagingSenderId: '280801840179',
    projectId: 'carrentalappflutter',
    authDomain: 'carrentalappflutter.firebaseapp.com',
    storageBucket: 'carrentalappflutter.firebasestorage.app',
    measurementId: 'G-Z3R3PJ64MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1L-IfDAFAWdIHHUZvHT20QstlKsCi_Ys',
    appId: '1:280801840179:android:39a4199f169aec1575e746',
    messagingSenderId: '280801840179',
    projectId: 'carrentalappflutter',
    storageBucket: 'carrentalappflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwv3ku7QnaUn9Xv_yIuJG3_YNKzT9wPP8',
    appId: '1:280801840179:ios:b99a30a120d9e2b575e746',
    messagingSenderId: '280801840179',
    projectId: 'carrentalappflutter',
    storageBucket: 'carrentalappflutter.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

}